name: Kitchen Oven Sensor
version: '0.0.14'
slug: kitchen_oven
description: Processes RTSP video streams for oven state and publishes to MQTT.
arch:
  - amd64
  - aarch64
init: false
map_addon_data: true
options:
  RTSP_URI: ""
  DAY_COLOR_THRESHOLD: 50
  NIGHT_LUMINANCE_THRESHOLD: 180
  NIGHT_BLOB_MIN_SIZE: 80
  NIGHT_BLOB_MAX_SIZE: 1000
  NIGHT_CONFIDENCE_THRESHOLD: 80
  ENABLE_NIGHT_MODE: true
  DEBUG_MODE: false
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_user: ""
  mqtt_pass: ""
  sensor_pin: 14
  MQTT_TOPIC_PREFIX: "homeassistant"
  MQTT_CLIENT_ID: "kitchen-camera-cli"
schema:
  RTSP_URI: str
  DAY_COLOR_THRESHOLD: int
  NIGHT_LUMINANCE_THRESHOLD: int
  NIGHT_BLOB_MIN_SIZE: int
  NIGHT_BLOB_MAX_SIZE: int
  NIGHT_CONFIDENCE_THRESHOLD: int
  ENABLE_NIGHT_MODE: bool
  DEBUG_MODE: bool
  mqtt_host: str
  mqtt_port: int
  mqtt_user: str?
  mqtt_pass: password?
  sensor_pin: int
  MQTT_TOPIC_PREFIX: str?
  MQTT_CLIENT_ID: str?
image: 'ghcr.io/jnlin/ha-kitchen-oven-sensor-{arch}'
