FROM freebsd/freebsd-runtime:15.1
RUN env ASSUME_ALWAYS_YES=yes pkg bootstrap && \
    env ASSUME_ALWAYS_YES=yes pkg update && \
    env ASSUME_ALWAYS_YES=yes pkg install -y ffmpeg
COPY kitchen-camera-bin /usr/local/bin/kitchen-camera
ENV RTSP_URI=""
ENV DETECTION_THRESHOLD="50"
ENTRYPOINT ["/usr/local/bin/kitchen-camera"]
