name: Lint and Test

on:
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  lint:
    name: Lint Go Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26'

      - name: Check Formatting
        working-directory: kitchen_oven
        run: |
          if [ -n "$(gofmt -l .)" ]; then
            echo "The following files are not formatted:"
            gofmt -l .
            exit 1
          fi

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          working-directory: kitchen_oven

  test:
    name: Run Go Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26'
          cache-dependency-path: kitchen_oven/go.sum

      - name: Run Tests
        working-directory: kitchen_oven
        run: go test -v ./...

  vulncheck:
    name: Run Go Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26'
          cache: true
          cache-dependency-path: kitchen_oven/go.sum
      - name: Run govulncheck
        uses: golang/govulncheck-action@v1
        with:
          work-dir: kitchen_oven

